version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: addania
      POSTGRES_PASSWORD: t3appgoals
      POSTGRES_DB: goalsdb
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
